language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pm90/react-example-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true pm90/react-example-travis npm run test
