language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pm90/react-example-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true pm90/react-example-travis npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "react-example-travis"
  env: "ReactExampleTravis-env"
  bucket_name: "elasticbeanstalk-eu-central-1-277367360328"
  bucket_path: "react-example-travis"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
